spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/usuarios/**

            - id: historico
              uri: lb://USER-SERVICE
              predicates:
                - Path=/historico/**

            - id: task-service
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/tarefas/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                allowedMethods:
                  - "*"
                allowedHeaders:
                  - "*"

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always